### ISSUE TITLE
Allow site-wide search to return results from variable labels

### ISSUE THREAD

**Issue by mrueschman** [nsrr/sleepdata.org#362]
(Only do this if somewhat straightforward - otherwise we will backlog)

We want to add some special labels to variables across datasets (e.g. for a specific type of AHI variable) in our ongoing harmonization efforts. We would like to allow users to pull up a list of these similar variables. In lieu of adding these technical codes to display names, having the site-wide search also parse variable labels could help.

Note: I have no idea how the search index gets built - or how it gets updated either? I actually found some "stale" results in the site-wide search, e.g. linking to variables that have since been changed and therefore no longer exist in a given dataset.

**Comment by remomueller** [comment]
So the labels aren't included currently (however will add them in the next commit), easy change. In order to remove stale results, you can reset the search cache using the following:

```
rails search:reset RAILS_ENV=production
```

This shouldn't need to be done that often, and it's something I'll run after adding the new search field to the index.
